fun a() {
  throw Error("err");
}

try {
  a();
} catch (Error e) {
  print e;
}
